# Generated by Django 4.2.7 on 2025-11-10 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Momento exacto de la lectura del sensor')),
                ('heart_rate', models.FloatField(help_text='Ritmo cardíaco en BPM (latidos por minuto)')),
                ('spo2', models.FloatField(help_text='Saturación de oxígeno en sangre (%)')),
                ('accel_x', models.FloatField(help_text='Aceleración en eje X (g)')),
                ('accel_y', models.FloatField(help_text='Aceleración en eje Y (g)')),
                ('accel_z', models.FloatField(help_text='Aceleración en eje Z (g)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(help_text='Dispositivo que envió los datos', on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='devices.device')),
            ],
            options={
                'verbose_name': 'Dato de Sensor',
                'verbose_name_plural': 'Datos de Sensores',
                'db_table': 'sensor_data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', 'timestamp'], name='sensor_data_device__b1be03_idx'), models.Index(fields=['timestamp'], name='sensor_data_timesta_97a1d1_idx'), models.Index(fields=['-timestamp'], name='sensor_data_timesta_ac587d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcessedMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateTimeField(db_index=True, help_text='Inicio de la ventana de tiempo')),
                ('window_end', models.DateTimeField(help_text='Fin de la ventana de tiempo')),
                ('hr_avg', models.FloatField(help_text='Promedio de ritmo cardíaco en la ventana (BPM)')),
                ('hr_max', models.FloatField(help_text='Ritmo cardíaco máximo en la ventana (BPM)')),
                ('hr_min', models.FloatField(help_text='Ritmo cardíaco mínimo en la ventana (BPM)')),
                ('hrv_rmssd', models.FloatField(blank=True, help_text='Variabilidad cardíaca - RMSSD (ms)', null=True)),
                ('hrv_sdnn', models.FloatField(blank=True, help_text='Variabilidad cardíaca - SDNN (ms)', null=True)),
                ('hr_trend', models.CharField(choices=[('stable', 'Estable'), ('increasing', 'Aumentando'), ('decreasing', 'Disminuyendo')], default='stable', help_text='Tendencia del ritmo cardíaco', max_length=20)),
                ('spo2_avg', models.FloatField(help_text='Promedio de SpO2 en la ventana (%)')),
                ('spo2_min', models.FloatField(help_text='SpO2 mínimo en la ventana (%)')),
                ('spo2_variance', models.FloatField(blank=True, help_text='Varianza de SpO2', null=True)),
                ('desaturation_count', models.IntegerField(default=0, help_text='Número de desaturaciones (caídas >3% o >4%)')),
                ('activity_level', models.FloatField(help_text='Nivel de actividad - magnitud RMS del acelerómetro')),
                ('movement_variance', models.FloatField(blank=True, help_text='Varianza del movimiento', null=True)),
                ('movement_entropy', models.FloatField(blank=True, help_text='Entropía del movimiento (inactividad o temblores)', null=True)),
                ('posture_angle', models.FloatField(blank=True, help_text='Ángulo de postura/inclinación del cuerpo (grados)', null=True)),
                ('fatigue_index', models.FloatField(db_index=True, help_text='Índice de fatiga calculado por ML (0-100)')),
                ('hr_activity_ratio', models.FloatField(blank=True, help_text='Ratio HR/Actividad (HR alta + baja actividad = fatiga)', null=True)),
                ('recovery_time', models.FloatField(blank=True, help_text='Tiempo de recuperación post-esfuerzo (minutos)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(help_text='Dispositivo del cual se procesaron los datos', on_delete=django.db.models.deletion.CASCADE, related_name='processed_metrics', to='devices.device')),
                ('employee', models.ForeignKey(help_text='Empleado al que pertenecen las métricas', limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='processed_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Métrica Procesada',
                'verbose_name_plural': 'Métricas Procesadas',
                'db_table': 'processed_metrics',
                'ordering': ['-window_start'],
                'indexes': [models.Index(fields=['employee', 'window_start'], name='processed_m_employe_b7ffbd_idx'), models.Index(fields=['fatigue_index'], name='processed_m_fatigue_952566_idx'), models.Index(fields=['-window_start'], name='processed_m_window__e018f5_idx'), models.Index(fields=['device', 'window_start'], name='processed_m_device__dcfab9_idx')],
            },
        ),
    ]
