# Generated by Django 4.2.7 on 2025-11-20 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la empresa cliente', max_length=255, unique=True, verbose_name='Nombre de la empresa')),
                ('contact_email', models.EmailField(help_text='Email principal de contacto de la empresa', max_length=255, verbose_name='Email de contacto')),
                ('contact_phone', models.CharField(blank=True, help_text='Teléfono de contacto de la empresa', max_length=20, null=True, verbose_name='Teléfono de contacto')),
                ('address', models.TextField(blank=True, help_text='Dirección física de la empresa', null=True, verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True, help_text='Si la empresa está activa y puede usar el servicio', verbose_name='Activa')),
                ('subscription_start', models.DateField(default=django.utils.timezone.now, help_text='Fecha de inicio del servicio', verbose_name='Inicio de suscripción')),
                ('subscription_end', models.DateField(blank=True, help_text='Fecha de fin del servicio (null = indefinido)', null=True, verbose_name='Fin de suscripción')),
                ('max_employees', models.IntegerField(default=50, help_text='Número máximo de empleados permitidos para esta empresa', verbose_name='Máximo de empleados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'companies',
                'ordering': ['-created_at'],
            },
        ),
    ]
