# Generated by Django 4.2.7 on 2025-11-10 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_identifier', models.CharField(help_text='Identificador único del dispositivo (ej: ESP32-001)', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Si el dispositivo está activo y en uso')),
                ('last_connection', models.DateTimeField(blank=True, help_text='Última vez que el dispositivo envió datos', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(help_text='Empleado al que está asignado el dispositivo', limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='device', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(help_text='Supervisor que gestiona este dispositivo', limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'db_table': 'devices',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee'], name='devices_employe_f98828_idx'), models.Index(fields=['supervisor'], name='devices_supervi_275fa1_idx'), models.Index(fields=['is_active'], name='devices_is_acti_9ea4e7_idx')],
            },
        ),
    ]
