# Generated by Django 4.2.7 on 2025-11-20 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '__first__'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece el dispositivo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='companies.company'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['company'], name='devices_company_8b43cd_idx'),
        ),
    ]
