# Generated by Django 5.2.8 on 2025-11-25 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_company_device_devices_company_8b43cd_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='supervisor',
            field=models.ForeignKey(help_text='Supervisor o Admin que gestiona este dispositivo', limit_choices_to={'role__in': ['supervisor', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
