# Generated by Django 5.2.8 on 2025-11-11 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Crear'), ('update', 'Actualizar'), ('delete', 'Eliminar'), ('login', 'Iniciar sesión'), ('logout', 'Cerrar sesión'), ('resolve_alert', 'Resolver alerta'), ('apply_recommendation', 'Aplicar recomendación'), ('assign_device', 'Asignar dispositivo'), ('other', 'Otra acción')], max_length=50, verbose_name='Acción')),
                ('resource_type', models.CharField(choices=[('user', 'Usuario'), ('supervisor', 'Supervisor'), ('employee', 'Empleado'), ('device', 'Dispositivo'), ('alert', 'Alerta'), ('recommendation', 'Recomendación'), ('system', 'Sistema')], max_length=50, verbose_name='Tipo de recurso')),
                ('resource_id', models.IntegerField(blank=True, null=True, verbose_name='ID del recurso')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Información adicional sobre la acción realizada', verbose_name='Detalles')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Actividad',
                'verbose_name_plural': 'Registros de Actividad',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='users_activ_timesta_622925_idx'), models.Index(fields=['user', '-timestamp'], name='users_activ_user_id_8a5363_idx'), models.Index(fields=['action', '-timestamp'], name='users_activ_action_04c071_idx'), models.Index(fields=['resource_type', 'resource_id'], name='users_activ_resourc_d01ee0_idx')],
            },
        ),
    ]
