# Generated by Django 4.2.7 on 2025-11-20 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '__first__'),
        ('users', '0003_customuser_department_customuser_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='admin',
        ),
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece (supervisores y empleados)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='companies.company', verbose_name='Empresa'),
        ),
    ]
