# Generated by Django 4.2.7 on 2025-11-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_company_alter_customuser_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Foto de perfil del usuario', null=True, upload_to='avatars/', verbose_name='Foto de perfil'),
        ),
    ]
