# Generated by Django 4.2.7 on 2025-11-10 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('break', 'Descanso'), ('task_redistribution', 'Redistribución de Tareas'), ('shift_rotation', 'Rotación de Turnos')], help_text='Tipo de recomendación', max_length=30)),
                ('description', models.TextField(help_text='Descripción detallada de la recomendación')),
                ('priority', models.IntegerField(default=3, help_text='Prioridad de 1 (más urgente) a 5 (menos urgente)')),
                ('based_on_data', models.JSONField(help_text='Métricas y datos que generaron esta recomendación')),
                ('is_applied', models.BooleanField(default=False, help_text='Si la recomendación fue aplicada')),
                ('applied_at', models.DateTimeField(blank=True, help_text='Momento en que se aplicó la recomendación', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='Empleado para el cual es la recomendación', limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='employee_recommendations', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(help_text='Supervisor que recibe la recomendación', limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recomendación de Rutina',
                'verbose_name_plural': 'Recomendaciones de Rutinas',
                'db_table': 'routine_recommendations',
                'ordering': ['priority', '-created_at'],
                'indexes': [models.Index(fields=['supervisor', 'is_applied'], name='routine_rec_supervi_882de8_idx'), models.Index(fields=['employee', 'is_applied'], name='routine_rec_employe_8e4d4d_idx'), models.Index(fields=['priority', '-created_at'], name='routine_rec_priorit_f9f505_idx')],
            },
        ),
        migrations.CreateModel(
            name='FatigueAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Momento en que se generó la alerta')),
                ('severity', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], db_index=True, help_text='Nivel de severidad de la alerta', max_length=10)),
                ('alert_type', models.CharField(help_text='Tipo de alerta (high_fatigue, low_spo2, high_hr, etc.)', max_length=50)),
                ('message', models.TextField(help_text='Mensaje descriptivo de la alerta')),
                ('fatigue_index', models.FloatField(help_text='Índice de fatiga en el momento de la alerta')),
                ('is_resolved', models.BooleanField(db_index=True, default=False, help_text='Si la alerta fue resuelta')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Momento en que se resolvió la alerta', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(help_text='Empleado al que se le generó la alerta', limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='fatigue_alerts', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Usuario que resolvió la alerta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(help_text='Supervisor que debe atender la alerta', limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta de Fatiga',
                'verbose_name_plural': 'Alertas de Fatiga',
                'db_table': 'fatigue_alerts',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['employee', 'is_resolved'], name='fatigue_ale_employe_e979de_idx'), models.Index(fields=['supervisor', 'is_resolved'], name='fatigue_ale_supervi_7bf9f1_idx'), models.Index(fields=['severity', '-timestamp'], name='fatigue_ale_severit_94d630_idx'), models.Index(fields=['-timestamp'], name='fatigue_ale_timesta_0ea219_idx')],
            },
        ),
    ]
