# Generated by Django 4.2.7 on 2025-11-25 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, help_text='ID del dispositivo ESP32 (ej: ESP32-001)', max_length=50)),
                ('status', models.CharField(choices=[('running', 'En Ejecución'), ('stopped', 'Detenido'), ('error', 'Error')], db_index=True, default='running', help_text='Estado actual del simulador', max_length=20)),
                ('fatigue_profile', models.CharField(choices=[('rested', 'Descansado (0-30%)'), ('normal', 'Normal (30-50%)'), ('tired', 'Cansado (50-70%)'), ('fatigued', 'Fatigado (70-85%)'), ('critical', 'Crítico (85-100%)')], default='normal', help_text='Perfil de fatiga del empleado simulado', max_length=20)),
                ('activity_mode', models.CharField(choices=[('resting', 'Reposo'), ('light', 'Actividad Ligera'), ('moderate', 'Actividad Moderada'), ('heavy', 'Actividad Intensa')], default='light', help_text='Modo de actividad del empleado', max_length=20)),
                ('base_heart_rate', models.IntegerField(default=70, help_text='Ritmo cardíaco base (BPM)')),
                ('base_spo2', models.FloatField(default=97.0, help_text='Saturación de oxígeno base (%)')),
                ('initial_fatigue', models.FloatField(default=20.0, help_text='Nivel inicial de fatiga (0-100)')),
                ('fatigue_rate', models.FloatField(default=0.5, help_text='Tasa de incremento de fatiga por minuto')),
                ('mqtt_broker', models.CharField(default='localhost', help_text='Dirección del broker MQTT', max_length=100)),
                ('mqtt_port', models.IntegerField(default=1883, help_text='Puerto del broker MQTT')),
                ('publish_interval', models.IntegerField(default=5, help_text='Intervalo de publicación en segundos')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='Momento en que se inició el simulador')),
                ('stopped_at', models.DateTimeField(blank=True, help_text='Momento en que se detuvo el simulador', null=True)),
                ('messages_sent', models.IntegerField(default=0, help_text='Número de mensajes MQTT enviados')),
                ('current_fatigue', models.FloatField(default=0.0, help_text='Nivel actual de fatiga')),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si el simulador falló', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Usuario que inició el simulador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_simulator_sessions', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Empleado para el cual se ejecuta el simulador', limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='simulator_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Simulador',
                'verbose_name_plural': 'Sesiones de Simulador',
                'db_table': 'simulator_sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='simulator_s_employe_de2157_idx'), models.Index(fields=['device_id', 'status'], name='simulator_s_device__127217_idx'), models.Index(fields=['-started_at'], name='simulator_s_started_8d6ff0_idx')],
            },
        ),
    ]
