# Generated by Django 4.2.7 on 2025-11-28 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0002_simulatorsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatiguealert',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='Momento en que se reconoció la alerta', null=True),
        ),
        migrations.AddField(
            model_name='fatiguealert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que reconoció la alerta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fatiguealert',
            name='is_acknowledged',
            field=models.BooleanField(db_index=True, default=False, help_text='Si la alerta fue reconocida/vista'),
        ),
    ]
