# Generated by Django 4.2.7 on 2025-11-30 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0003_fatiguealert_acknowledged_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_type', models.CharField(choices=[('fatigue', 'Fatiga/Cansancio'), ('headache', 'Dolor de cabeza'), ('dizziness', 'Mareo'), ('nausea', 'Náuseas'), ('muscle_pain', 'Dolor muscular'), ('eye_strain', 'Fatiga visual'), ('stress', 'Estrés'), ('difficulty_concentrating', 'Dificultad para concentrarse'), ('shortness_of_breath', 'Dificultad para respirar'), ('other', 'Otro')], help_text='Tipo de síntoma reportado', max_length=30, verbose_name='Tipo de síntoma')),
                ('severity', models.CharField(choices=[('mild', 'Leve'), ('moderate', 'Moderado'), ('severe', 'Severo')], default='mild', help_text='Nivel de severidad del síntoma', max_length=10, verbose_name='Severidad')),
                ('description', models.TextField(blank=True, help_text='Descripción adicional del síntoma (opcional)', null=True, verbose_name='Descripción')),
                ('is_reviewed', models.BooleanField(default=False, help_text='Si el reporte fue revisado por el supervisor', verbose_name='Revisado')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Momento en que se revisó el reporte', null=True, verbose_name='Fecha de revisión')),
                ('notes', models.TextField(blank=True, help_text='Notas o comentarios del supervisor', null=True, verbose_name='Notas del supervisor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reporte')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('employee', models.ForeignKey(help_text='Empleado que reporta el síntoma', limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='symptom_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Usuario que revisó el reporte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_symptom_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Síntoma',
                'verbose_name_plural': 'Reportes de Síntomas',
                'db_table': 'symptom_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', '-created_at'], name='symptom_rep_employe_f01e95_idx'), models.Index(fields=['symptom_type', '-created_at'], name='symptom_rep_symptom_3fd130_idx'), models.Index(fields=['severity', '-created_at'], name='symptom_rep_severit_ff8a10_idx'), models.Index(fields=['is_reviewed', '-created_at'], name='symptom_rep_is_revi_88cb66_idx')],
            },
        ),
    ]
