# Generated by Django 4.2.7 on 2025-11-30 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0004_symptomreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_type', models.CharField(choices=[('coffee', 'Café/Snack'), ('lunch', 'Almuerzo'), ('rest', 'Descanso general'), ('medical', 'Médico'), ('personal', 'Personal'), ('stretch', 'Estiramiento/Ejercicio')], help_text='Tipo de descanso', max_length=20, verbose_name='Tipo de descanso')),
                ('scheduled_date', models.DateField(help_text='Fecha del descanso', verbose_name='Fecha programada')),
                ('scheduled_time', models.TimeField(help_text='Hora de inicio del descanso', verbose_name='Hora programada')),
                ('duration_minutes', models.IntegerField(choices=[(15, '15 minutos'), (30, '30 minutos'), (45, '45 minutos'), (60, '1 hora'), (90, '1 hora 30 minutos'), (120, '2 horas')], default=30, help_text='Duración del descanso en minutos', verbose_name='Duración (minutos)')),
                ('reason', models.TextField(blank=True, help_text='Razón o motivo del descanso (opcional)', null=True, verbose_name='Razón')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], db_index=True, default='pending', help_text='Estado actual del descanso programado', max_length=15, verbose_name='Estado')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Momento en que se revisó la solicitud', null=True, verbose_name='Fecha de revisión')),
                ('reviewer_notes', models.TextField(blank=True, help_text='Notas o comentarios del supervisor', null=True, verbose_name='Notas del supervisor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('employee', models.ForeignKey(help_text='Empleado que programa el descanso', limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_breaks', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Supervisor que revisó la solicitud', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_breaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Descanso Programado',
                'verbose_name_plural': 'Descansos Programados',
                'db_table': 'scheduled_breaks',
                'ordering': ['scheduled_date', 'scheduled_time'],
                'indexes': [models.Index(fields=['employee', '-scheduled_date'], name='scheduled_b_employe_a829b0_idx'), models.Index(fields=['status', 'scheduled_date'], name='scheduled_b_status_e8ce9a_idx'), models.Index(fields=['scheduled_date', 'scheduled_time'], name='scheduled_b_schedul_f4dd2e_idx')],
            },
        ),
    ]
