# Generated by Django 4.2.7 on 2025-12-09 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_device_supervisor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0005_scheduledbreak'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(db_index=True, help_text='Tipo de alerta (HIGH_HEART_RATE, LOW_SPO2, etc.)', max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('CRITICAL', 'Crítica')], db_index=True, default='WARNING', help_text='Severidad de la alerta', max_length=10)),
                ('message', models.TextField(help_text='Mensaje descriptivo de la alerta')),
                ('heart_rate', models.FloatField(blank=True, help_text='Ritmo cardíaco en el momento de la alerta (BPM)', null=True)),
                ('spo2', models.FloatField(blank=True, help_text='SpO2 en el momento de la alerta (%)', null=True)),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Momento en que se generó la alerta')),
                ('is_acknowledged', models.BooleanField(db_index=True, default=False, help_text='Si la alerta fue vista/reconocida')),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='Momento en que se reconoció la alerta', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('acknowledged_by', models.ForeignKey(blank=True, help_text='Usuario que reconoció la alerta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_device_alerts', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(help_text='Dispositivo que generó la alerta', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='devices.device')),
                ('employee', models.ForeignKey(help_text='Empleado asociado a la alerta', limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='device_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta de Dispositivo',
                'verbose_name_plural': 'Alertas de Dispositivos',
                'db_table': 'device_alerts',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['employee', '-timestamp'], name='device_aler_employe_1aec96_idx'), models.Index(fields=['device', '-timestamp'], name='device_aler_device__24bac6_idx'), models.Index(fields=['alert_type', '-timestamp'], name='device_aler_alert_t_c1d887_idx'), models.Index(fields=['is_acknowledged', '-timestamp'], name='device_aler_is_ackn_6fdb95_idx')],
            },
        ),
    ]
